{"uuid": "cd5cec21-2062-4797-a3fb-1f33f4518b7c", "children": ["28ea62c8-d4f5-4d7b-b637-79723f71471f"], "befores": [{"name": "setup_SansConnexionUser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchWindowException: Message: no such window: window was already closed\n  (Session info: chrome=99.0.4844.83)\nStacktrace:\n0   chromedriver                        0x0000000102c3b960 chromedriver + 4438368\n1   chromedriver                        0x0000000102bd103c chromedriver + 4001852\n2   chromedriver                        0x000000010282630c chromedriver + 156428\n3   chromedriver                        0x0000000102817ae4 chromedriver + 96996\n4   chromedriver                        0x0000000102812514 chromedriver + 75028\n5   chromedriver                        0x000000010287dc58 chromedriver + 515160\n6   chromedriver                        0x000000010284a400 chromedriver + 304128\n7   chromedriver                        0x0000000102bfe4a8 chromedriver + 4187304\n8   chromedriver                        0x0000000102c14588 chromedriver + 4277640\n9   chromedriver                        0x0000000102c19268 chromedriver + 4297320\n10  chromedriver                        0x0000000102c14dd0 chromedriver + 4279760\n11  chromedriver                        0x0000000102bf42ec chromedriver + 4145900\n12  chromedriver                        0x0000000102c2df0c chromedriver + 4382476\n13  chromedriver                        0x0000000102c2e080 chromedriver + 4382848\n14  chromedriver                        0x0000000102c4228c chromedriver + 4465292\n15  libsystem_pthread.dylib             0x00000001b64614ec _pthread_start + 148\n16  libsystem_pthread.dylib             0x00000001b645c2d0 thread_start + 8\n\n", "trace": "  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1122, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/_pytest/fixtures.py\", line 917, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/TestCases/conftest.py\", line 69, in setup_SansConnexionUser\n    hp.clickaccepterTCF()\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/PageObjects/HomePage.py\", line 23, in clickaccepterTCF\n    element = self.wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, Locators.accepter_btnTCF_CSS)))\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/support/wait.py\", line 78, in until\n    value = method(self._driver)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/support/expected_conditions.py\", line 326, in _predicate\n    target = driver.find_element(*target)  # grab element at locator\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 1248, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/abdi.bileh17/Documents/Selenium/Projet_test_v0/env/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1648029114708, "stop": 1648029120442}], "start": 1648029114708, "stop": 1648029120537}